# this is the script for downloading all video...............

# Importing PyQt5........................
from PyQt5.QtCore import QThread, pyqtSignal   # For QThreads and QtSignal ...
from PyQt5.QtGui import QPixmap                # For QPixmap .................
# Video downloading package .............
import yt_dlp
# Importing json ........................
import json
# Requests module for thumbnail ........
import requests
# Time module for calculating time .....
import time
# For Threading ..........................
import concurrent.futures
# For Sound notification .................
import winsound
# Class imports ..........................
from YT_Check import *
# For notification ........................
from plyer import notification

# All the formats ..........................

#All Downloading formats.............
Formats = ['bestvideo*+bestaudio/best', 'bestaudio/best',
           'bestvideo[height<=1080]+bestaudio/best[height<=1080]', 'bestvideo[height<=720]+bestaudio/best[height<=720]',
           'bestvideo[height<=480]+bestaudio/best[height<=480]', 'bestvideo[height<=360]+bestaudio/best[height<=360]',
           'bestvideo[height<=240]+bestaudio/best[height<=240]', 'bestvideo[height<=144]+bestaudio/best[height<=144]']


class Thread_DownloadUV(QtCore.QThread):
           
    # Signals for Ui updates.....       
    ProgressCount = QtCore.pyqtSignal(int)      # Progress Count.........
    DownloadSpeed = QtCore.pyqtSignal(str)      # Downloading speed......
    TimeRemains = QtCore.pyqtSignal(str)        # Remaining time ........
    Downloaded_So_Far = QtCore.pyqtSignal(str)  # Size of file that downloaded so far .......
  def __init__(self, parent):
        QThread.__init__(self, parent)
        self.MainCode = parent
           
        # method for class. ............
        self.YTV_Checks = Thread_ChecksUV(self)

        # Variables for app ...................
        self.Link = ''
        self.VideoFormat = ''
        self.Format_Requested = ''
        self.Video_folder = ''
        self.The_link = ''
        self.Requested_Sub_lang = ''
        self.is_running = True
  
